- type: entity
  parent: BaseItem
  id: AccessConfiguratorTypan
  name: конфигуратор доступа
  description: Используется для изменения требований уровня доступа к шлюзам и другим запираемым объектам.
  suffix: Тайпан
  components:
    - type: EmitSoundOnLand
      sound:
        path: /Audio/Items/multitool_drop.ogg
    - type: Sprite
      sprite: _Mini/Objects/Tools/access_configurator.rsi
      state: icon
    - type: Item
      size: Small
    - type: Clothing
      sprite: _Mini/Objects/Tools/access_configurator.rsi
      quickEquip: false
      slots:
        - Belt
    - type: AccessOverrider
      accessLevels:
      - TypanArmory
      - TypanAtmospherics
      - TypanCargo
      - TypanCommand
      - TypanCommunicationsOfficer
      - TypanEngineering
      - TypanMaint
      - TypanMedical
      - TypanProtection
      - TypanResearchDirector
      - TypanScience
      - TypanService
      - TypanTechnicalOperationsSupervisor
      - TypanVault
      - TypanExternal
      privilegedIdSlot:
        name: id-card-console-privileged-id
        ejectSound: /Audio/Machines/id_swipe.ogg
        insertSound: /Audio/Weapons/Guns/MagIn/batrifle_magin.ogg
        ejectOnBreak: true
        swap: false
        whitelist:
          components:
          - IdCard
      denialSound:
        path: /Audio/Machines/custom_deny.ogg
      doAfter: 0.5
    - type: UserInterface
      interfaces:
        enum.AccessOverriderUiKey.Key:
          type: AccessOverriderBoundUserInterface
    - type: ActivatableUI
      key: enum.AccessOverriderUiKey.Key
      requiresComplex: true
      requireActiveHand: false
      singleUser: true
    - type: ItemSlots
    - type: ContainerContainer
      containers:
        AccessOverrider-privilegedId: !type:ContainerSlot
