using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Client.UserInterface.CustomControls;
using Content.Shared._Eternal.Paper;
using Robust.Client.GameObjects;
using Robust.Shared.Utility;
using Robust.Client.UserInterface;

namespace Content.Client._Eternal.Paper;

[GenerateTypedNameReferences]
public sealed partial class ChameleonPenWindow : DefaultWindow
{
    public event Action<Color, string>? OnSave;

    public ChameleonPenWindow()
    {
        RobustXamlLoader.Load(this);
        SaveButton.OnPressed += _ =>
        {
            var color = ColorSelector.Color;
            var text = SignatureTextEdit.Text.Trim();
            OnSave?.Invoke(color, text);
        };
        CancelButton.OnPressed += _ => Close();
    }

    public void SetInitial(Color? color, string? text)
    {
        ColorSelector.Color = color ?? Color.White;
        SignatureTextEdit.Text = text ?? string.Empty;
    }
}

public sealed class ChameleonPenBui : BoundUserInterface
{
    private ChameleonPenWindow? _window;

    public ChameleonPenBui(EntityUid owner, Enum uiKey) : base(owner, uiKey) { }

    protected override void Open()
    {
        base.Open();

        _window = this.CreateWindow<ChameleonPenWindow>();
        _window.OnSave += (color, text) =>
        {
            SendMessage(new ChameleonPenBuiSetMessage(color, text));
            Close();
        };
    }

    protected override void UpdateState(BoundUserInterfaceState state)
    {
        if (state is not ChameleonPenBuiState s)
            return;

        _window?.SetInitial(s.ForgedSignatureColor, s.ForgedSignatureText);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
        {
            _window?.Dispose();
        }
    }
}
