using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class RecipeUnlockCardControl : Control
{
    public RecipeUnlockCardControl(TechnologyPrototype technology, LatheRecipePrototype proto, IPrototypeManager prototypeManager, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        var discipline = prototypeManager.Index<TechDisciplinePrototype>(technology.Discipline);
        Background.ModulateSelfOverride = discipline.Color;

        string displayName;
        if (!string.IsNullOrEmpty(proto.Name))
        {
            displayName = Loc.GetString(proto.Name);
        }
        else if (proto.Result.HasValue && prototypeManager.TryIndex(proto.Result.Value, out var entProto) && entProto is EntityPrototype itemProto)
        {
            displayName = Loc.GetString(itemProto.Name);
        }
        else
        {
            displayName = Loc.GetString("research-console-recipe-no-name");
        }
        NameLabel.SetMessage(displayName);

        if (proto.Result.HasValue)
            Showcase.Texture = sprite.Frame0(prototypeManager.Index(proto.Result.Value));
    }
}
