using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class TechnologyPrereqCardControl : Control
{
    public TechnologyPrereqCardControl(TechnologyPrototype technology, IPrototypeManager prototypeManager, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        var discipline = prototypeManager.Index<TechDisciplinePrototype>(technology.Discipline);
        Background.ModulateSelfOverride = discipline.Color;

        NameLabel.SetMessage(Loc.GetString(technology.Name));
        Showcase.Texture = sprite.Frame0(technology.Icon);
    }
}
