- type: job
  id: TypanChef
  name: job-name-typan-chef
  playTimeTracker: TypanChef
  description: Повар из далёкого космоса.
  startingGear: SyndicateChef
  icon: "JobIconTypanChef"
  supervisors: job-supervisors-typan-telecommunications-officer
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 6000
  access:
  - TypanService
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skills # Corvax-Next-Skills
        skills:
        - Butchering

- type: startingGear
  id: SyndicateChef
  equipment:
    ears: ClothingHeadsetAltSyndicate
    jumpsuit: ClothingUniformJumpsuitTypanChef
    back: ClothingBackpackSyndicate
    outerClothing: ClothingOuterApronTypanChef
    shoes: ClothingShoesColorBlack
    id: SyndiPDAChef
