- type: job
  id: TypanRD
  name: job-name-typan-rd
  playTimeTracker: TypanRD
  description: Директор исследований из далёкого космоса.
  startingGear: SyndicateRD
  icon: "JobIconSyndicateRD"
  supervisors: job-supervisors-typan-syndicate
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 6000
    - !type:OverallPlaytimeRequirement
      time: 21600
    - !type:AgeRequirement
      requiredAge: 24
  access:
  - TypanResearchDirector
  - TypanScience
  - SyndicateAgent
  - TypanCommand
  - TypanVault
  - TypanExternal
  - TypanEngineering
  - TypanMaint
- type: startingGear
  id: SyndicateRD
  equipment:
    eyes: ClothingEyesGlassesHiddenSecurity
    ears: ClothingHeadsetAltSyndicate
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsRDTypan
    id: SyndiPDARD
    back: ClothingBackpackSyndicate
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
