using System.Text.RegularExpressions;
using Content.Shared._Eternal.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Eternal.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class BankUiFragment : BoxContainer
{
    public Action<BankAccountLinkMessage>? OnLinkAttempt;

    private bool _accountLinkActive;

    private readonly string _lineEditPattern = "[^0-9]";

    public Action<BankChangePinMessage>? OnChangePinAttempt;

    public BankUiFragment()
    {
        RobustXamlLoader.Load(this);

        AccountLinkButton.OnPressed += _ =>
        {
            _accountLinkActive = true;
            UpdateAccountLinkUi();
        };

        ChangePinShowButton.OnPressed += _ =>
        {
            ChangePinShowButton.Visible = false;
            ChangePinPanel.Visible = true;
        };

        ChangePinCancelButton.OnPressed += _ =>
        {
            ChangePinPanel.Visible = false;
            ChangePinShowButton.Visible = true;
            OldPinLineEdit.Text = string.Empty;
            NewPinLineEdit.Text = string.Empty;
            ChangePinResultLabel.Visible = false;
        };

        SavePinButton.OnPressed += _ =>
        {
            ChangePinResultLabel.Visible = false;
            if (OldPinLineEdit.Text.Length != 4 || NewPinLineEdit.Text.Length != 4)
            {
                ChangePinResultLabel.Text = Loc.GetString("bank-program-ui-change-pin-invalid");
                ChangePinResultLabel.Visible = true;
                return;
            }
            if (!int.TryParse(OldPinLineEdit.Text, out var oldPin) || !int.TryParse(NewPinLineEdit.Text, out var newPin))
            {
                ChangePinResultLabel.Text = Loc.GetString("bank-program-ui-change-pin-invalid");
                ChangePinResultLabel.Visible = true;
                return;
            }
            OnChangePinAttempt?.Invoke(new BankChangePinMessage(oldPin, newPin));
            // Hide panel after attempt (UX: like account link)
            ChangePinPanel.Visible = false;
            ChangePinShowButton.Visible = true;
            OldPinLineEdit.Text = string.Empty;
            NewPinLineEdit.Text = string.Empty;
        };

        OldPinLineEdit.OnTextChanged += _ =>
        {
            ValidateLineEdit(OldPinLineEdit, 4);
        };

        NewPinLineEdit.OnTextChanged += _ =>
        {
            ValidateLineEdit(NewPinLineEdit, 4);
        };

        LinkCancelButton.OnPressed += _ =>
        {
            _accountLinkActive = false;
            UpdateAccountLinkUi();
        };

        PinLineEdit.OnTextChanged += _ =>
        {
            ValidateLineEdit(PinLineEdit, 4);
        };

        AccountLineEdit.OnTextChanged += _ =>
        {
            ValidateLineEdit(AccountLineEdit, 6);
        };

        LinkConfirmButton.OnPressed += _ =>
        {
            if (PinLineEdit.Text.Length != 4 || AccountLineEdit.Text.Length != 6)
                return;

            var accountId = int.Parse((string) AccountLineEdit.Text);
            var pin = int.Parse((string) PinLineEdit.Text);
            AccountLinkResultLabel.Visible = true;
            _accountLinkActive = false;
            OnLinkAttempt?.Invoke(new BankAccountLinkMessage(accountId, pin));
        };
    }

    public void UpdateState(BankCartridgeUiState state)
    {
        var accountLinked = state.AccountId != null;

        AccountLinkMessageLabel.Text = state.AccountLinkMessage;
        AccountLinkResultLabel.Text = state.AccountLinkResult;

        if (!string.IsNullOrEmpty(state.AccountLinkResult))
        {
            if (state.AccountLinkResult.Contains("PIN-код успешно изменен") || 
                state.AccountLinkResult.Contains("PIN successfully changed"))
            {
                OldPinLineEdit.Text = string.Empty;
                NewPinLineEdit.Text = string.Empty;
                ChangePinPanel.Visible = false;
                ChangePinShowButton.Visible = true;
                ChangePinResultLabel.Text = state.AccountLinkResult;
                ChangePinResultLabel.Visible = true;
            }
            else if (state.AccountLinkResult.Contains("PIN") || 
                     state.AccountLinkResult.Contains("Wrong old PIN") ||
                     state.AccountLinkResult.Contains("Invalid PIN"))
            {
                ChangePinResultLabel.Text = state.AccountLinkResult;
                ChangePinResultLabel.Visible = true;
            }
            else
            {
                ChangePinResultLabel.Visible = false;
            }
        }
        else
        {
            ChangePinResultLabel.Visible = false;
        }

        LinkedAccount.Visible = accountLinked;
        NoLinkedAccountLabel.Visible = !accountLinked;

        if (accountLinked)
        {
            LinkedAccountNumberLabel.Text = Loc.GetString("bank-program-ui-account-number-text",
                ("account", state.AccountId!.Value));
            LinkedAccountNameLabel.Text = Loc.GetString("bank-program-ui-account-owner-text",
                ("owner", state.OwnerName));
            LinkedAccountBalanceLabel.Text = Loc.GetString("atm-ui-balance", ("balance", state.Balance));
            UpdateAccountLinkUi();
            return;
        }

        NoLinkedAccountLabel.Text = Loc.GetString("bank-program-ui-no-account");
        UpdateAccountLinkUi();
    }


    private void UpdateAccountLinkUi()
    {
        AccountLinkButton.Visible = !_accountLinkActive;
        AccountLink.Visible = _accountLinkActive;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        LinkConfirmButton.Disabled = PinLineEdit.Text.Length != 4 || AccountLineEdit.Text.Length != 6;
        SavePinButton.Disabled = OldPinLineEdit.Text.Length != 4 || NewPinLineEdit.Text.Length != 4;
    }

    private void ValidateLineEdit(LineEdit lineEdit, int length)
    {
        var text = Regex.Replace(lineEdit.Text, _lineEditPattern, string.Empty);

        if (text.Length > length)
        {
            text = text[..length];
        }

        lineEdit.Text = text;
    }
}
